version: '3'
services:
  write-api:
    build: ./src/WriteApi
  read-api:
    build: ./src/ReadApi
  write-database:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "CqRs@setuptalk2019"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
  read-database:
    image: mongo:3.0
    ports:
      - 27017:27017
